steps:
  - name: gcr.io/cloud-builders/docker
    env:
      - DOCKER_BUILDKIT=1
    args:
      - build
      - --build-arg
      - NEXT_PUBLIC_FIREBASE_API_KEY=${_FIREBASE_API_KEY}
      - --build-arg
      - NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=${_FIREBASE_AUTH_DOMAIN}
      - --build-arg
      - NEXT_PUBLIC_FIREBASE_PROJECT_ID=$PROJECT_ID
      - -t
      - ${_IMAGE}
      - .
images:
  - ${_IMAGE}
options:
  logging: CLOUD_LOGGING_ONLY
